steps:
  # Create docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tdlabs-quarkus-demo-google-cloud-run', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tdlabs-quarkus-demo-google-cloud-run']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy',
      'tdlabs-quarkus-demo-google-cloud-run',
      '--image', 'gcr.io/$PROJECT_ID/tdlabs-quarkus-demo-google-cloud-run',
      '--platform', 'managed',
      '--region', 'europe-west1',
      '--allow-unauthenticated',
      '--set-env-vars', 'DISABLE_SIGNAL_HANDLERS=true',
      '--memory','64M'
    ]

# Image name
images: ['gcr.io/$PROJECT_ID/tdlabs-quarkus-demo-google-cloud-run']
